language: 'python'

python: 
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install coveralls

services: 
  - postgres

before-script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - export DB_NAME="test"
  - export DB_USER="postgres"
  - export DB_PASS=""
  - export DB_HOST="localhost"
  - export DB_PORT="5432"

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=authors manage.py test

after-success:
  - coveralls

