language: 'python'

python: 
  - '3.7-dev'

install:
  - pip install -r requirements.txt
  - pip install coveralls

services: 
  - postgresql

before-script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - export DB_NAME="authors_haven"
  - export DB_USER="kwame"
  - export DB_PASS=""
  - export DB_HOST="localhost"
  - export DB_PORT="5432"
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=authors manage.py test

after-success:
  - coveralls

