language: 'python'

python: 
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install coveralls

services: 
  - postgresql

before-script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python --version

after-success:
  - coveralls

