language: 'python'

python: 
  - '3.7-dev'
  - '3.6'


install:
  - pip install -r requirements.txt
  - pip install coveralls

services: 
  - postgresql

before-script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source=authors manage.py test

after-success:
  - coveralls
