# Generated by Django 2.1.4 on 2019-01-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_following'),
        ('authentication', '0002_user_is_verified'),
    ]

    operations = [
    ]
