# Generated by Django 2.1.5 on 2019-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20190121_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_notification_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
