# Generated by Django 2.1.4 on 2019-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190121_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'I PREFER NOT TO SAY')], default='N', error_messages={'incorrect_format': 'dd'}, max_length=10),
        ),
    ]
