# Generated by Django 2.1.4 on 2019-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20190121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(error_messages={'required': 'first name'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'I PREFER NOT TO SAY')], default='N', max_length=10),
        ),
    ]
