# Generated by Django 2.1.4 on 2019-01-17 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190117_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
