# Generated by Django 2.1.4 on 2019-01-18 07:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190117_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
    ]
