# Generated by Django 2.1.4 on 2019-01-21 07:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190121_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, default='No image', max_length=255, null=True),
        ),
    ]
