# Generated by Django 2.1.4 on 2019-01-23 12:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_taglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagList',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
