# Generated by Django 2.1.4 on 2019-01-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_favoritearticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='body',
            new_name='is_favorited',
        ),
    ]
