# Generated by Django 2.1.4 on 2019-01-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190123_1219'),
        ('articles', '0011_auto_20190124_1750'),
    ]

    operations = [
    ]
