# Generated by Django 2.1.4 on 2019-01-23 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_auto_20190123_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritearticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favoritearticle',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteArticle',
        ),
    ]
