# Generated by Django 2.1.5 on 2019-01-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190128_0629'),
        ('articles', '0013_merge_20190125_1538'),
    ]

    operations = [
    ]
