# Generated by Django 2.1.5 on 2019-01-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_merge_20190125_1538'),
        ('articles', '0014_merge_20190128_0757'),
    ]

    operations = [
    ]
