# Generated by Django 2.1.5 on 2019-01-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_merge_20190128_0914'),
        ('articles', '0014_merge_20190128_1209'),
    ]

    operations = [
    ]
