# Generated by Django 2.1.4 on 2019-01-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20190123_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='slug',
            new_name='article',
        ),
    ]
