# Generated by Django 2.1.5 on 2019-01-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20190124_0706'),
        ('articles', '0013_merge_20190125_1538'),
    ]

    operations = [
    ]
