# Generated by Django 2.1.5 on 2019-01-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190123_1219'),
        ('articles', '0017_auto_20190124_0706'),
    ]

    operations = [
    ]
