# Generated by Django 2.1.5 on 2019-01-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_merge_20190125_1317'),
        ('articles', '0018_merge_20190125_1242'),
    ]

    operations = [
    ]
