# Generated by Django 2.1.5 on 2019-01-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_merge_20190128_0903'),
        ('articles', '0019_merge_20190128_0612'),
    ]

    operations = [
    ]
