# Generated by Django 2.1.5 on 2019-01-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190128_0913'),
        ('articles', '0015_merge_20190128_0914'),
    ]

    operations = [
    ]
