# Generated by Django 2.1.5 on 2019-01-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_merge_20190128_1245'),
        ('articles', '0016_merge_20190128_1532'),
    ]

    operations = [
    ]
