# Generated by Django 2.1.4 on 2019-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_merge_20190128_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='selected_text',
            field=models.TextField(null=True),
        ),
    ]
