# Generated by Django 2.1.5 on 2019-01-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_merge_20190128_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
    ]
