# Generated by Django 2.1.4 on 2019-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_comment_selected_text'),
        ('articles', '0023_auto_20190129_1219'),
    ]

    operations = [
    ]
