# Generated by Django 2.1.5 on 2019-01-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_merge_20190129_0617'),
        ('articles', '0023_auto_20190129_1219'),
    ]

    operations = [
    ]
