# Generated by Django 2.1.5 on 2019-01-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20190129_1219'),
        ('articles', '0016_auto_20190130_1258'),
    ]

    operations = [
    ]
