# Generated by Django 2.1.4 on 2019-01-31 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0024_merge_20190130_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('selected_text', models.TextField(blank=True, null=True)),
                ('start_highlight_position', models.IntegerField(blank=True, null=True)),
                ('end_highlight_position', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='articles.Article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='selected_text',
        ),
    ]
