# Generated by Django 2.1.5 on 2019-02-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_merge_20190130_1511'),
        ('articles', '0024_merge_20190130_0649'),
    ]

    operations = [
    ]
