# Generated by Django 2.1.5 on 2019-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_historicalcomment'),
        ('articles', '0025_merge_20190201_0800'),
    ]

    operations = [
    ]
