# Generated by Django 2.1.4 on 2019-02-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20190131_1219'),
        ('articles', '0024_merge_20190130_0649'),
    ]

    operations = [
    ]
