# Generated by Django 2.1.4 on 2019-02-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_merge_20190201_0800'),
        ('articles', '0026_merge_20190201_0623'),
    ]

    operations = [
    ]
