# Generated by Django 2.1.5 on 2019-02-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_merge_20190201_1306'),
        ('articles', '0026_merge_20190201_1108'),
    ]

    operations = [
    ]
