# Generated by Django 2.1.5 on 2019-02-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_merge_20190202_1446'),
        ('articles', '0028_merge_20190202_1740'),
    ]

    operations = [
    ]
