# Generated by Django 2.1.5 on 2019-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_merge_20190203_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighttextmodel',
            name='selected_text',
            field=models.TextField(blank=True),
        ),
    ]
