# Generated by Django 2.1.5 on 2019-02-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_merge_20190202_1354'),
        ('articles', '0029_merge_20190203_0728'),
    ]

    operations = [
    ]
