# Generated by Django 2.1.5 on 2019-02-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_merge_20190203_1430'),
        ('articles', '0030_auto_20190203_1345'),
    ]

    operations = [
    ]
