# Generated by Django 2.1.5 on 2019-02-23 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0030_merge_20190203_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ratings',
            field=models.ManyToManyField(blank=True, default=[], related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='highlighttextmodel',
            name='selected_text',
            field=models.TextField(blank=True),
        ),
    ]
