# Generated by Django 2.1.5 on 2019-02-23 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20190223_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
