# Generated by Django 2.1.5 on 2019-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_merge_20190203_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.URLField(blank=True, default='https://cdn0.iconfinder.com/data/icons/mtt-web-icons/139/article-512.png'),
        ),
    ]
