# Generated by Django 2.1.5 on 2019-02-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20190224_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
