# Generated by Django 2.1.5 on 2019-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20190224_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
