# Generated by Django 2.1.5 on 2019-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_remove_article_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.URLField(default='https://cdn0.iconfinder.com/data/icons/mtt-web-icons/139/article-512.png'),
        ),
    ]
