# Generated by Django 2.1.5 on 2019-02-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20190224_1110'),
        ('articles', '0036_auto_20190224_0611'),
    ]

    operations = [
    ]
